prevent double compilation in tests

diff --git a/run_diff_tests b/run_diff_tests
--- a/run_diff_tests
+++ b/run_diff_tests
@@ -3,12 +3,13 @@
 set -euo pipefail
 
 readonly ROOT="$(git rev-parse --show-toplevel)"
-cd "$ROOT/protoc-gen-elm"
-
-GO111MODULE=on go build -o ../elm-protobuf-test ./cmd/protoc-gen-elm
-
-readonly ELM_PLUGIN="${ROOT}/elm-protobuf-test"
 readonly TEST_ROOT="${ROOT}/test-diffs"
+readonly ELM_PLUGIN="${ROOT}/elm-protobuf-test"
+
+if [[ ! -f "${ELM_PLUGIN}" ]]; then
+    echo "compiled test plugin required"
+    exit 1
+fi
 
 for TEST in "${TEST_ROOT}"/*/; do
     TEST="${TEST%*/}" # strip  trailing "/"
diff --git a/run_elm_tests b/run_elm_tests
--- a/run_elm_tests
+++ b/run_elm_tests
@@ -2,14 +2,18 @@
 
 set -euo pipefail
 
-cd protoc-gen-elm
-GO111MODULE=on go build -o ../elm-protobuf-test ./cmd/protoc-gen-elm
-cd ..
+readonly ROOT="$(git rev-parse --show-toplevel)"
+readonly TEST_PLUGIN="${ROOT}/elm-protobuf-test"
+
+if [[ ! -f "${TEST_PLUGIN}" ]]; then
+    echo "compiled test plugin required"
+    exit 1
+fi
 
 protoc \
     --proto_path=./tests/proto \
     --elm_out=./tests \
-    --plugin=protoc-gen-elm=./elm-protobuf-test \
+    --plugin=protoc-gen-elm="${TEST_PLUGIN}" \
     ./tests/proto/*.proto
 
 elm-test 
